[RN-13] Expo implementation
ContentSquare/react-native-sample-app pull request #14
Opened 2022-11-01 10:56 UTC by fannytavart

<img width="869" alt="image" src="https://user-images.githubusercontent.com/19344809/199218141-17d87ba2-f83a-484c-89fb-1534fcc5b46e.png">

2023-01-05 15:24 UTC, Gguigre approved these changes

2023-01-09 11:25 UTC, CyberDandy approved these changes

2023-01-10 16:22 UTC, CyberDandy requested changes
I believe for all of those you should add a */ in front, otherwise you'll be adding unwanted files to the repo as it is looking for all files at the root of the project.

2023-01-11 14:54 UTC, CyberDandy approved these changes
LGTM

2023-01-11 14:59 UTC, merged